# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Enterprise Integration (c091862c-e1ab-44f1-876b-e55133fadc1a)'
    subscriptionId: 'c091862c-e1ab-44f1-876b-e55133fadc1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'SebsB2B'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sebdeveloper142/OrdersIntegration/main/ServiceBus/servicebus-template.json'
    csmParametersFileLink: 'LogicApp/ServiceBus/servicebus-parameters.json'
    deploymentMode: 'Incremental'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
